SAP/cloud-sdk-java

.github/workflows/blackduck.yaml
.pipeline/config.yml

BLI: https://github.com/SAP/cloud-sdk-java-backlog/issues/280
Follow-up for: https://github.com/SAP/cloud-sdk-java/pull/25#discussion_r1308362078

Read Blackduck excludes from modules-inventory.json

---

.github/workflows/build-sanity.yaml
.github/workflows/build.yaml
.pipeline/config.yml
.pipeline/scripts/print-coverage.py
pom.xml

Part of BLI: https://github.com/SAP/cloud-sdk-java-backlog/issues/282

Enforce threshold for JaCoCo and improve config

---

.github/workflows/blackduck.yaml
.github/workflows/build-sanity.yaml
.github/workflows/build.yaml
.pipeline/scripts/notify.py

BLI https://github.com/SAP/cloud-sdk-java-backlog/issues/282

Notify via slack in case CI workflow on main fails

---

.pipeline/config.yml
codestyle/checkstyle.xml

BLI: https://github.com/SAP/cloud-sdk-java-backlog/issues/282

Add checkstyle rule for TODO and FIXME comments

---

.github/workflows/build-sanity.yaml

Fix verification: https://github.com/SAP/cloud-sdk-java/actions/runs/6348262135

Fix scheduled sanity pipeline

---

cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoader.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java

This PR fixes a recursive loop for DwC On Premise destinations
Make sure the original test is not degraded

Used ProxyHandler in MegacliteDestination connectivity test

---

cloudplatform/resilience/pom.xml
cloudplatform/resilience/src/main/java/com/sap/cloud/sdk/cloudplatform/resilience/ResilienceDecorator.java
cloudplatform/resilience/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience/ResilienceDecoratorTest.java

BLI: https://github.com/SAP/cloud-sdk-java-backlog/issues/337
Alternative to #113

Fix: Silently Ignore Resilience for multiple ResilienceDecorationStrategies - Alternative

---

.github/PULL_REQUEST_TEMPLATE.md

Small additional change that allows the PR to be linked in the issue itself.
Closes SAP/cloud-sdk-java-backlog#316

feat: Update PR template to automatically close associated issue

---

.pipeline/config.yml
cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/DefaultThreadContextExecutorService.java
cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/LazyProperty.java
cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/SSLContextFactory.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/VdmEntity.java
datamodel/odata-v4/odata-v4-generator/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/generator/CodeModelClassGenerator.java
datamodel/odata-v4/odata-v4-generator/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/generator/EntitySetProcessor.java
datamodel/odata-v4/odata-v4-generator/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/generator/NavigationPropertyMethodsGenerator.java
datamodel/odata-v4/odata-v4-generator/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/generator/EntitySetProcessorTest.java
datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/EntityLink.java
datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/FluentHelperFactory.java
datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/VdmObject.java
datamodel/odata/odata-generator/src/main/java/com/sap/cloud/sdk/datamodel/odata/generator/NamespaceClassGenerator.java
testutil/testutil-core/src/main/java/com/sap/cloud/sdk/testutil/ThreadContextInvocationInterceptor.java

This PR fixes various true positive PMD warnings.

fix: various PMD warnings

---

bom/pom.xml

Update some dependencies
taken from V4

Update some dependencies

---

datamodel/odata-v4/odata-v4-generator-maven-plugin/pom.xml
datamodel/odata/odata-generator-maven-plugin/pom.xml
datamodel/openapi/openapi-generator-maven-plugin/pom.xml
pom.xml

Remove Unit 4 configuration related leftovers.

chore: JUnit 5 Migration Cleanup

---

CONTRIBUTING.md
README.md

SAP/cloud-sdk-java-backlog#345
Expanded the ReadMe for legibility and additional resources, including use cases, documentation links, and table of contents.

readme expanded and formatted

---

cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcHeaderUtils.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/security/DwcPrincipalFacadeTest.java

chore: Remove unused DwC constants

---

archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/controllers/HelloWorldController.java
archetypes/spring-boot3/src/main/resources/archetype-resources/pom.xml
pom.xml

Updates Spring Core to fix [CVE-2023-34053](https://nvd.nist.gov/vuln/detail/CVE-2023-34053) and Spring Boot to 3.2.0.
[Successful E2E test run](https://sdk-v2.cpe.c.eu-de-1.cloud.sap/job/end-to-end-tests/view/Cloud%20SDK%20v5/job/v5-scp-cf-spring/181/)

chore: Update Spring

---

.github/workflows/prepare_release.yml

Fix release pipeline

---

cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/GetOrComputeSingleDestinationCommand.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/GetOrComputeDestinationCommandTest.java

Fixes a bug introduced with #190

fix: [Destination] Fix Error Handling when Principal is Unavailable

---

datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/exception/ODataResponseErrorParsingTest.java
pom.xml

[Java15+] Enable text blocks

---

.pipeline/scripts/set-release-versions.py

Minor Improvement to ensure our README is always up to date 📈

chore: [DevOps] Automatically Update Readme upon Release

---

pom.xml

Remove Jetty dependency version declaration

---

.github/workflows/build.yaml

SAP/cloud-sdk-java-backlog#400
This enables PRs from forks

fix: Enable PRs from fork

---

release_notes.md

SAP/cloud-sdk-java-backlog#363
This PR adds the missed release notes for #260.

chore: Add release notes for archetype update

---

.github/workflows/dependabot-release-notes.yaml

SAP/cloud-sdk-java-backlog#196.
This PR fixes a few left-overs from #265.
* Successful Workflow Run: https://github.com/SAP/cloud-sdk-java/actions/runs/7799324510
* Updated PR: #277

fix: Dependabot Release Notes Automation

---

release_notes.md

(Automation didn't clean up after 5.3.0)

Fix/Prepare release notes for 5.4.0

---

.github/workflows/perform-release.yml

Fix typo in pipeline.
The secret name was not matching.

GPGP - GPG or PGP - GG WP

---

module-inventory.json
release_notes.md
s4hana/rfc/pom.xml

This PR is related to the BLI [#412 Test SJB 2.0 release candidates](https://github.com/SAP/cloud-sdk-java-backlog/issues/412).
It will enable the TomEE JCo app to be E2E tested: [[v5] Test SJB 2.0](https://github.tools.sap/cloudsdk/TomEE-JCo-test/pull/44#top) (it works locally)
[Documentation PR](https://github.com/SAP/cloud-sdk/pull/1718)

Publish the RFC module

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
release_notes.md

Adds an implementation for the AI Core service binding.

feat: Support AI Core by default in Service Binding Destination Loading

---

datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
datamodel/odata-v4/odata-v4-core/src/test/resources/ODataClientBatchResponseParsingUnitTest/BatchReadsAndWritesErrorResponseWithoutChangeset.txt

Follow up of [feat: Allow access to failed batch request](https://github.com/SAP/cloud-sdk-java/pull/347#top)

fix: Follow up of #347

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultServiceBindingDestinationLoaderChain.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/IdentityAuthenticationServiceBindingDestinationLoader.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/IdentityAuthenticationServiceBindingDestinationLoaderTest.java
release_notes.md

Kinda amazing this never caused a stackoverflow and wasn't detected by tests..

fix: [Destinations] Fix NPE on Using Bound Services Backed by IAS

---

.github/workflows/dependabot-automerge.yaml

Try fix GH merger again

---

datamodel/openapi/openapi-generator/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorIntegrationTest.java

Fix unit test validation in OpenAPI Generator

---

pom.xml

Remove Kotlin from dependencies

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2IntegrationTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
release_notes.md

SAP/cloud-sdk-java-backlog#450.

fix: [IAS] ZTIS for Subscriber Tenants when using IAS

---

archetypes/spring-boot3/src/main/resources/archetype-resources/pom.xml

SAP/cloud-sdk-java-backlog#452
Dependency updates

Updated Spring Boot to 3.3.0

---

pom.xml

Remove dependency jakarta.xml.bind-api

---

cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationService.java
cloudplatform/connectivity-destination-service/src/main/resources/META-INF/services/com.sap.cloud.sdk.cloudplatform.connectivity.DestinationFacade
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/GetOrComputeDestinationCommandTest.java

Javadoc change that we forgot for v5

Javadoc fix

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/AuthenticationType.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationType.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ProxyType.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/SecurityConfigurationStrategy.java
cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceRetrievalStrategy.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTokenExchangeStrategy.java
codestyle/sdk_specific_pmd_rules.xml
datamodel/datamodel-metadata-generator/src/main/java/com/sap/cloud/sdk/datamodel/metadata/generator/MetadataApiSpecificUsage.java
datamodel/fluent-result/src/main/java/com/sap/cloud/sdk/result/ElementName.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataFormat.java
datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/s4hana/datamodel/odata/adapter/ODataField.java
datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/model/ApiMaturity.java
s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/ParameterKind.java
s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/SoapNamespace.java
s4hana/s4hana-core/src/main/java/com/sap/cloud/sdk/s4hana/serialization/MessageType.java

https://github.com/SAP/cloud-sdk-java-backlog/issues/456

Fix custom PMD rules

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultDestination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderTest.java
release_notes.md

[Related use case](https://sap.stackenterprise.co/questions/58219)

feat: [Destinations] Destination Builder Property Removal

---

cloudplatform/caching/src/main/java/com/sap/cloud/sdk/cloudplatform/cache/SerializableCacheKey.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/exception/ODataConnectionException.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/exception/ODataException.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/exception/ODataResponseException.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/exception/ODataSerializationException.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/exception/ODataServiceErrorException.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/FilterExpressionArithmetic.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/expression/FilterExpressionTemporal.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestAction.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestCreate.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestGeneric.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestUpdate.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/adapter/JacksonVdmEnumDeserializer.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/BatchRequestBuilder.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/CountRequestBuilder.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/GetAllRequestBuilder.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/GetByKeyRequestBuilder.java
datamodel/odata/odata-core/src/main/java/com/sap/cloud/sdk/datamodel/odata/helper/FluentHelperFunction.java
s4hana/rfc/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/AbstractRemoteFunctionRequest.java
s4hana/s4hana-connectivity/src/main/java/com/sap/cloud/sdk/s4hana/connectivity/ErpTypeSerializer.java
s4hana/s4hana-core/src/main/java/com/sap/cloud/sdk/s4hana/serialization/ErpInteger.java
s4hana/s4hana-core/src/main/java/com/sap/cloud/sdk/s4hana/serialization/StringBasedErpType.java

Let's make the SAP Cloud SDK compatible.
I'm using `temurin-22.0.1`
I think most of the `this-escape` warnings are too difficult to fix, without breaking API and behavior.

Fix JDK22 compiler warnings

---

.github/workflows/perform-release.yml

Fix the broken Perform Release

Fix Staging Deploy in Release workflow

---

datamodel/openapi/openapi-generator/pom.xml
datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/GenerationConfigurationConverter.java
datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/model/GenerationConfiguration.java
pom.xml

[OpenAPI Generator] Omit unnecessary dependency declaration

---

README.md

The CI Badge shows the latest status of any branch or PR.
It should show only the main branch.

CI Badge fix

---

cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DwcHeaderProvider.java
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteDestinationFactory.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DwcHeaderProviderTest.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java
release_notes.md

https://github.tools.sap/deploy-with-confidence/issues/issues/2552#issuecomment-7439955

[DwC] Limit DwC Headers when Connecting to Megaclite

---

datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestGeneric.java
datamodel/odata-client/src/test/resources/ODataClientQueryBatchUnitTest/BatchAllRequestBody.txt
datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/EncodedQueryTest.java
datamodel/odata/odata-core/src/test/resources/ODataV2BatchFunctionImportTest/BatchRequestFunctionImportWithPostWithCustomHeader.txt
datamodel/odata/odata-core/src/test/resources/ODataV2BatchRequestUnitTest/BatchRequestWithCustomHeaders.txt

This PR changes OData headers and parameters to follow a deterministic order.

fix: [DevOps] Improve Test Reliability

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandler.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationTest.java
release_notes.md

Alternative solution to:
https://github.com/SAP/cloud-sdk-java/pull/567
Related issue:
https://github.com/SAP/cloud-sdk-java/issues/550
* Low footprint change.
* No API change.
* Limit behavior change to proxy header provider only.

Fix multiple invocations of `DefaultHttpDestinationBuilderProxyHandler#handle`

---

datamodel/openapi/openapi-api-sample/pom.xml
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/Soda.java
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/SodaWithId.java
datamodel/openapi/openapi-api-sample/src/main/resources/sodastore.json
datamodel/openapi/openapi-api-sample/src/test/java/com/sap/cloud/sdk/datamodel/openapi/sample/api/DeserializationTest.java
datamodel/openapi/openapi-api-sample/src/test/java/com/sap/cloud/sdk/datamodel/openapi/sample/api/SerializationTest.java
datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/modelEnum.mustache
datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/modelInnerEnum.mustache
release_notes.md

User issue;
https://github.com/SAP/cloud-sdk-java/issues/566
See documentation;
https://openapi-generator.tech/docs/generators/openapi/

feat: [OpenAPI Generator] Allow for wildcard `nullable=false` enum deserialization

---

datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/Order.java
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/OrderWithTimestamp.java
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/Soda.java
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/SodaWithId.java
datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/pojo.mustache
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-builder/output/com/sap/cloud/sdk/services/builder/model/NewSoda.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-builder/output/com/sap/cloud/sdk/services/builder/model/Soda.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-builder/output/com/sap/cloud/sdk/services/builder/model/UpdateSoda.java
release_notes.md

We've noticed Checkstyle warnings for missing JavaDoc, let's fix that.

[OpenAPI] Improve JavaDoc Generation for default constructor on model classes

---

cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Accessor.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Cache.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5CacheBuilder.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Factory.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5FactoryBuilder.java
release_notes.md

Related ticket:
https://github.com/SAP/cloud-sdk-java-backlog/issues/461

[Stabilize] Remove `@Beta` annotation from Apache HttpClient 5 API

---

datamodel/odata-v4/odata-v4-generator/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/generator/EdmUtils.java
datamodel/odata-v4/odata-v4-generator/src/test/resources/oDataGeneratorIntegrationTest/actionsAndFunctionsTest/input/actionsAndFunctions.edmx
datamodel/odata-v4/odata-v4-generator/src/test/resources/oDataGeneratorIntegrationTest/actionsAndFunctionsTest/output/testcomparison/services/ActionsAndFunctionsService.java
datamodel/odata-v4/odata-v4-generator/src/test/resources/oDataGeneratorIntegrationTest/actionsAndFunctionsTest/output/testcomparison/services/DefaultActionsAndFunctionsService.java
release_notes.md

Implementation for #643, see the [OData spec for more details](https://docs.oasis-open.org/odata/odata/v4.0/csprd01/part3-csdl/odata-v4.0-csprd01-part3-csdl.html#_Toc355092889)

feat: [OData V4] TypeDefinition Support

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/BatchRequestBuilder.java
release_notes.md

feat: [OData V4] Improve BatchRequestBuilder

---

.github/workflows/perform-release.yml

This PR fixes two small bugs in the `perform-release.yml`.

fix: Bugfixes in perform-release script

---

.github/workflows/dependabot-automerge.yaml

fix: Moved dependabot-automerge to Tuesday

---

datamodel/openapi/openapi-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojoUnitTest.java

The test wasn't executed with maven.

chore: [OpenAPI] Fix broken test

---

dependency-bundles/bom/pom.xml

SAP/cloud-sdk-java-backlog#448.
Updated service binding library version to 0.21.0

chore: Updated service binding version to 0.21.0

---

datamodel/odata/odata-generator/src/main/java/com/sap/cloud/sdk/datamodel/odata/generator/MetadataFileUtils.java
release_notes.md

fix: [OData V2]: Disable Validation in the absense of DOCTYPE

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultDestination.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultDestinationTest.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapter.java
release_notes.md

[Destinations] Improve Detection and Masking of Secrets in Debug Logs

---

archetypes/spring-boot3/src/main/resources/archetype-resources/manifest.yml

Related https://github.com/sap-tutorials/Tutorials/issues/23939

chore: Increase archetype SapMachineJre version

---

release_notes.md

fix: Fix release notes
