SAP/cloud-sdk-java

.github/workflows/build.yaml

The `needs` property also has to contain `build`, since otherwise its output cannot be read.

Fix reading the version from build in deploy-snapshots step

---

.github/workflows/build.yaml
.github/workflows/prepare_release.yml
.pipeline/scripts/generate-release-artifacts.py

For unknown reasons, the Maven GPG Plugin cannot successfully deploy snapshots to the Artifactory. This PR adds the optinoal "--with-signing" flag to the Python script which generates the wrapper POM used for deploying artifacts. Only in the Prepare Release pipeline, this flag is passed. For the other CI pipelines, the JARs are not signed anymore as before.

Fix build pipeline after merging deployment to Maven Central

---

cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationRetrievalStrategyResolver.java
cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationRetrievalStrategy.java
cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationRetrievalStrategyResolverTest.java
cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationLoaderTest.java
release_notes_next_major.md

Removed deprecated `ScpCfDestinationRetrievalStrategy.CURRENT_TENANT_THEN_PROVIDER`.

322 - remove CURRENT_TENANT_THEN_PROVIDER

---

.github/workflows/build-sanity.yaml

See for example a [failed run](https://github.com/SAP/cloud-sdk-java/actions/runs/6418792336/job/17427294605). The error message in the exception above the error log output tells the story.

Force Java 17 for CodeQL, same as in normal CI workflow

---

.pipeline/config.yml
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DwcConfiguration.java
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBinding.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingTest.java

This PR is part of the work on backlog item [#297](https://github.com/SAP/cloud-sdk-java-backlog/issues/297). This problem was uncovered after the use of ScpCf destination API on the v5 `DwC-test-app`.
The changes in this PR include:
- A new `dwcConfiguration` field has been added to the `MegacliteServiceBinding` class, it can be (re)set after the binding is built.
- The `getCredentials()` method in the `MegacliteServiceBinding` class has been updated to return a map containing the `tenantid` and `providerTenantId`, or, throws the Exception created by `DwcConfiguration`.
- The `testPropertiesOfTheOpenSourceServiceBinding()` method in the `MegacliteServiceBindingTest` class has been updated to include a mock of the `DwcConfiguration` class and to check that the `tenantid` is correctly set …

Fix: Add `providerTenantId` to `MegacliteServiceBinding`

---

javadoc.overview.html

This PR addresses the task outlined in backlog item [#281](https://github.com/SAP/cloud-sdk-java-backlog/issues/281). It includes updates to the Javadoc Overview Page as part of the process of moving all active development to the OSS repository.
The changes in this PR are as follows:
- The HTML tag in the `javadoc.overview.html` file now includes the `lang="en"` attribute to specify the language of the document.
- The description of the Virtual Data Model (VDM) for the S4/HANA APIs has been updated to include generators.
- The links to the `cloudplatform` and `s4hana` packages have been removed and replaced with plain text.
- The `s4hana` package reference has been replaced with `datamodel`, which includes implementations and generators for OpenAPI and OData VDMs.
Please review the …

fix: Update Javadoc Overview Page

---

cloudplatform/cloudplatform-connectivity-scp-cf/pom.xml
cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationServiceAdapter.java
cloudplatform/cloudplatform-connectivity-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationServiceAdapterTest.java
cloudplatform/cloudplatform-core-scp-cf/pom.xml
cloudplatform/cloudplatform-core-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/ScpCfCloudPlatform.java
cloudplatform/cloudplatform-core-scp-cf/src/test/java/com/sap/cloud/sdk/cloudplatform/ScpCfCloudPlatformTest.java
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBinding.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingTest.java

DwC apps cannot call `ScpCfCloudPlatform` without the `DWC_APPLICATION` env var. This was introduced in #98.
Here is the intended stacktrace from top to bottom
- `DwcConfiguration` throws
- then `MegacliteServiceBinding` catches and returns an empty map
- then `ScpCfCloudPlatform` works normally
-  then `ScpCfDestinationServiceAdapter` throws if the map is empty.
- What should the message thrown by `ScpCfDestinationServiceAdapter` be?
- _Maybe it should be `"No DWC_APPLICATION environment variable defined. Cannot determine the provider account id."`. Not sure if there is a scenario in which the Adapter doesn't find `tenantid` while the binding is not DwC_
- Do the new test dependencies cause a problem?
- Is there still a need for `DwcConfiguration` to be public to help customer test their …

Change ScpCf modules behaviour with DwC bindings

---

cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ScpCfDestinationRetrievalStrategy.java

The DwC test app previously used `DwcDestinationRetrievalStrategy.ofIdentifier()`.
The app has been changed to use ScpCf.
This new method will be used in [this DwC-test-app pull request.](https://github.wdf.sap.corp/MA/DwC-Test-App/pull/124)

Fix DwC-test-app: Made `ScpCfDestinationRetrievalStrategy.ofIdentifier()` public

---

datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestGeneric.java
datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultGeneric.java
datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultGenericTest.java

This ports the change done in https://github.wdf.sap.corp/MA/sdk/pull/8631 from v4 to v5.

Migrate OData header deduplication

---

datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestResultMultipartGeneric.java
datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
datamodel/odata-v4/odata-v4-core/src/test/resources/ODataClientBatchResponseParsingUnitTest/BatchOnlyReadsMissingRequest.txt
datamodel/odata-v4/odata-v4-core/src/test/resources/ODataClientBatchResponseParsingUnitTest/BatchOnlyReadsMissingResponse.txt

**This PR is a cherry-pick of a [v4 PR](https://github.wdf.sap.corp/MA/sdk/pull/8636#top).** It addresses the issue raised in the backlog item [#342](https://github.com/SAP/cloud-sdk-java-backlog/issues/342). It improves the exception handling in the `ODataRequestResultMultipartGeneric` class by providing a more informative error message when an `IndexOutOfBoundsException` is encountered.
The main change is in the `ODataRequestResultMultipartGeneric` class. Previously, if a subrequest in a batch returned a status code such as 400, an `IndexOutOfBoundsException` would be thrown. This has been replaced with an `ODataResponseException` that provides a more informative error message. The error message indicates the position of the missing batch response item and the total number of items in …

fix: Improve exception handling in ODataRequestResultMultipartGeneric class

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilderTest.java
release_notes_next_major.md

Small improvement inspired by the requirement to set a custom name [here](https://github.com/cap-js/docs/pull/534/files#diff-81ee32ad88239ef1cf29d9f9cc1553192e5ec7e6d480c4be3868979f20db7416L284).
This is enabled by the recent improvements we did to the destination and its builder 🥳

feat: Improve OAuthDestinationBuilder

---

bom/pom.xml
pom.xml
release_notes_next_major.md

Reverts SAP/cloud-sdk-java#131
Revert this dependency update since it broke out Java 8 compatibility.

Revert "chore: update caffeine major version"

---

pom.xml

This pull request addresses the backlog item [#319 Fix Blackduck v5 findings](https://github.com/SAP/cloud-sdk-java-backlog/issues/319).
The changes in this PR include an update to the versions of `olingo-v4` and `olingo-v2` in the `pom.xml` file. The versions have been updated from `4.9.0` to `4.10.0` and `2.0.12` to `2.0.13` respectively.

fix: Update versions of olingo-v4 and olingo-v2 in pom.xml

---

cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessor.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessorTest.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java

SAP/cloud-sdk-java-backlog#209
This PR changes the connectivity service binding for megaclite to no longer be registered by default. This is necessary as otherwise there would be two bindings available in case shared orbits are used.
Users will have to register the connectivity binding explicitly, similar to the destination service binding.

fix: DwC Connectivity Service Auto Configuration

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultDestinationLoader.java

This is effectively the same fix that we did to the `HttpClientAccessor`. The API is used by the CAP multi tenancy implementation, both in cds-services and in the DwC Spring Utils.

fix: CAP API Compatibility

---

pom.xml

Fixes an issue with test execution where the encoding config was not passed on to forked JVMs. Does some further POM cleanup.

chore: Parent POM Cleanup & Test Setup Improvements

---

cloudplatform/connectivity-dwc/pom.xml
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteConnectivityProxyInformationResolver.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteConnectivityProxyInformationResolverTest.java

SAP/cloud-sdk-java-backlog/issues/359
This PR refactors our `MegacliteConnectivityProxyInformationResolver` to use a `Caffeine` cache instead of our regular resilience cache.
The reason for this change is that our resilience caching is not working in case the application doesn't provide a proper JCache implementation.
With this change, our caching behavior no longer depends on the actually used dependencies in the customer application.
Additionally, this PR changes the caching behavior:
Instead of having two separates caches (one for the auth token and another one for the proxy URL), we are now using a single cache for the entire megaclite response (which contains both the token as well as the proxy URL).
As a consequence, the proxy URL will also be cached PER TENANT and has a short …

refactor: use caffeine for caching insetad of regular resilience api

---

archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/Application.java
archetypes/spring-boot3/src/main/resources/archetype-resources/pom.xml

SAP/cloud-sdk-java-backlog#307
Workarounds were needed for an SDK application to use Java 17. Now that the SDK only supports Java 17, these workarounds can be removed in Spring applications
🟢[Successful test run](https://sdk-v2.cpe.c.eu-de-1.cloud.sap/job/end-to-end-tests/view/Cloud%20SDK%20v5/job/v5-scp-cf-spring-java17-jakarta/154/)

Rollback artifact workarounds

---

archetypes/spring-boot3/src/main/resources/archetype-resources/application/pom.xml
archetypes/spring-boot3/src/main/resources/archetype-resources/application/src/main/java/__packageInPathFormat__/Application.java
archetypes/spring-boot3/src/main/resources/archetype-resources/integration-tests/src/test/java/__packageInPathFormat__/HelloWorldControllerTest.java
archetypes/spring-boot3/src/main/resources/archetype-resources/pom.xml

Follow-up of #164 and #166
Compare [this](https://github.wdf.sap.corp/MA/sdk/pull/8627) and [this](https://github.wdf.sap.corp/MA/sdk/pull/8664)  change on V4.
[Successful E2E Test Run](https://sdk-v2.cpe.c.eu-de-1.cloud.sap/job/end-to-end-tests/view/Cloud%20SDK%20v5/job/v5-scp-cf-spring-xsuaa/142/)

fix: XSUAA Usage in Spring Boot Archetype

---

bom/pom.xml
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OnPremTest.java
pom.xml

This PR cleans up obsolete dependency convergence entries, increases outdated dependencies and more.

chore: Dependency Cleanup

---

.pipeline/config.yml

This PR adjusts the BlackDuck scan to no longer produce false positives based on older versions of our own modules.
[Successful run](https://github.com/SAP/cloud-sdk-java/actions/runs/7086109307)
There is a follow-up BLI to check out if Mend can perform better: SAP/cloud-sdk-java-backlog#365

fix: Improve BlackDuck Scan

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandler.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/PrincipalPropagationMode.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandlerTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ConnectivityServiceTest.java
release_notes_next_major.md

This PR renames the `PrincipalPropagationMode` entries to more expressive terms. Intentionally breaking the API so that any users actively notice the change and switch to the recommended (default) `TOKEN_FORWARDING`

fix: PrincipalPropagationMode

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoaderTest.java

This PR fixes the error handling in our `OAuth2ServiceBindingDestinationLoader` in cases where a (customer-provided) `OAuth2PropertySupplier` throws an Exception in any of the getters.

fix: error handling in OAuth2ServiceBindingDestinationLoader

---

archetypes/spring-boot3/src/main/resources/archetype-resources/integration-tests/pom.xml

Fixes a dependency conflict between XSUAA testing lib and Spring Boot.

fix: XSUAA Test Code in Archetype for Spring Boot 3.2.0

---

.github/workflows/perform_release.yml

SAP/cloud-sdk-java-backlog#358.
This PR changed our `perform-release` pipeline to automatically publish our release once the deployment succeeds.
That way, no more manual action is needed to finish the release.

fix: automatically release once the deployment succeeds

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/UriBuilder.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/UriPathMerger.java
cloudplatform/connectivity-apache-httpclient4/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/UriPathMergerTest.java
release_notes.md

Closes SAP/cloud-sdk-java-backlog#382.
Invalid domain names break our `UriPathMerger`, which sends a broken URI to the HttpClient.

[Fix] Invalid Destination Domain Throws

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/UriBuilder.java
release_notes.md

[[Fix] Invalid Destination Domain Throws](https://github.com/SAP/cloud-sdk-java/pull/189#top) removed a public method by accident. This PR re-adds the deleted method but deprecated.
I manually edited UriPathMerger to use the deprecated method and manually ran the UriPathMergerTest👍

Re-Added `UriBuilder.build` but deprecated

---

cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/AuthTokenHeaderProvider.java
release_notes.md

This PR adds a warning which is logged when headers for an expired auth token are accessed.
We could also consider throwing an exception, but for now I didn't do that for two reasons:
* The destination service could send incorrect expiry information, or there may be a grace period
* Headers may be accessed also outside of actually executing requests

feat: [Destinations] Warn on Expired Auth Token Usage

---

.pipeline/scripts/generate-release-artifacts.py

SAP/cloud-sdk-java-backlog#358.
This PR provides **a quick-fix** for our archetype deployment issue.
The fix has been tested as part of [my fork repository](https://github.com/Johannes-Schneider/cloud-sdk-java), where I was able to successfully publish version `0.0.2`.
<details>
<summary>Deployment Difference</summary>
The **old** deployment that contains _spring-boot3-5.0.0.**maven-archetype**_ (incorrect file extension):
---
The **new** deployment that contains _spring-boot3-0.0.2.**jar**_ (correct file extension):
</details>

fix: Archetype Release

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java

This PR adds an implementation for `toString` on `DefaultHttpDestination`. In SDK 4 the `ScpCfHttpDestination` implemented this for cases where the destination was retrieved from the BTP Destination Service.
Which properties to log exactly may be questionable.. Compare the [current state in SDK 4](https://github.wdf.sap.corp/MA/sdk/blob/main/v4/cloudplatform/cloudplatform-connectivity-scp/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/AbstractScpDestination.java#L104).
Idea: Log only a few properties which represent enough information and are known to not contain confidential data. Represent that more properties may be present via `, ...)` (otherwise it may be misleading, readers may think the other properties are missing).
Alternatives:
1. print all properties known to be …

feat: [Destinations] Add toString Implementation for DefaultHttpDestination

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandler.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationService.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/GetOrComputeSingleDestinationCommandWithoutAllDestinationsTest.java

Follow up to #190 
This PR hardens the `GetOrComputeSingleDestinationCommandWithoutAllDestinationsTest` by mocking the `DestinationServiceV1Reponse` (instead of `HttpDestination`). That way the relevant logic from `DestinationServiceFactory` is now tested (instead of mocked).

chore: [Destinations] Improve Test for Destination Service Option Combinations

---

archetypes/spring-boot3/src/main/resources/archetype-resources/integration-tests/pom.xml

Is this even necessary?
Current "Jetty 11" is not natively compatible with current "Spring Boot", without [adjustments](https://github.com/spring-projects/spring-boot/issues/33044).

Remove jetty bom from archetype

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ComplexDestinationPropertyFactory.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceFactoryTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ForwardAuthTokenTest.java
release_notes.md

SAP/cloud-sdk-java-backlog#401
This PR allows destinations retrieved from the Destination Service with Authentication Type `NO_AUTHENTICATION` to evaluate the `forwardAuthToken` parameter.
This means any incoming JWT will be forwarded to the target of the destination if the `forwardAuthToken` is set to true and the Authentication Type is either unset or set to `NO_AUTHENTICATION`.

feat: Extend AuthToken Forwarding

---

.github/dependabot.yaml

SAP/cloud-sdk-java-backlog#311.
Configures dependabot to create PRs for updating dependencies. This will probably require further tuning, but it is easier to do that once an initial state has been merged to main.

chore: [DevOps] Enable Dependabot

---

.github/workflows/build.yaml

This PR addresses the issue of PR build failures when the PR is created via a fork instead of a branch. The root cause of this issue was identified to be related to a specific step in the build workflow. This PR modifies the condition for running the 'Test Report' step in the build workflow to ensure it does not run on a forked repository. This change is expected to enable successful PR builds from forked repositories.
The following changes have been made in this PR:
- Modified the condition for running the 'Test Report' step in the build workflow. The step will now only run if the repository is not a forked one.
The backlog item associated with this PR can be found [here](https://github.com/SAP/cloud-sdk-java-backlog/issues/400).
Please review the changes made in the build workflow file …

fix: Modify build workflow to prevent failures from forked repositories

---

.github/dependabot.yaml

SAP/cloud-sdk-java-backlog#111, follow up of #236 
This PR adds a grouping rule for updating actions, adds further exclusions and improves commit messages.
Unfortunately archetypes don't seem to work.

chore: [DevOps] Improve Dependabot Config

---

.github/actions/deploy-snapshot/action.yaml

SAP/cloud-sdk-java-backlog#318.
Follow-up of #259 
This PR fixes an issue with our snapshot deployment.
As per [actions/setup-java documentation](https://github.com/actions/setup-java):
> * `server-username`: Environment variable name for the username for authentication to the Apache Maven repository. Default is GITHUB_ACTOR.
> * `server-password`: Environment variable name for password or token for authentication to the Apache Maven repository. Default is GITHUB_TOKEN.
So when using the `setup-java` action, it is expected to pass the environment variable names instead of their content, which is now fixed with this PR.

fix: Snapshot Deployment

---

.github/actions/scan-with-blackduck/action.yaml
.github/workflows/blackduck.yaml
.github/workflows/continuous-integration.yaml

SAP/cloud-sdk-java-backlog#318.
Follow-up of #259 
This PR fixes our BlackDuck scan, which is apparently not able to access secrets as it is within a re-usable action.
🟢 [Successful BlackDuck Scan](https://github.com/SAP/cloud-sdk-java/actions/runs/7830330456/job/21364100366)

fix: BlackDuck Scan

---

.github/workflows/dependabot-release-notes.yaml
.pipeline/scripts/dependabot-release-notes.py

This PR fixes the Dependabot Release Notes automation in two regards:
1. The GH action was incorrectly skipped (e.g. #284) as the initial `if` condition was apparently incorrect.
2. The python script failed if there are multiple updates to the same dependency, even if the updates are for the exact same version.

fix: Dependabot Release Notes Generation

---

cloudplatform/connectivity-destination-service/pom.xml
cloudplatform/connectivity-oauth/pom.xml
cloudplatform/security/pom.xml
cloudplatform/security/src/test/java/com/sap/cloud/sdk/cloudplatform/security/principal/OAuth2AuthTokenPrincipalExtractorTest.java
cloudplatform/tenant/pom.xml
codestyle/sdk_specific_pmd_rules.xml
datamodel/odata-v4/odata-v4-generator-maven-plugin/pom.xml
datamodel/odata-v4/odata-v4-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/generator/DataModelGeneratorMojoTest.java
datamodel/odata/odata-generator-maven-plugin/pom.xml
datamodel/odata/odata-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/odata/generator/DataModelGeneratorMojoTest.java
datamodel/openapi/openapi-generator-maven-plugin/pom.xml
datamodel/openapi/openapi-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojoIntegrationTest.java
datamodel/openapi/openapi-generator-maven-plugin/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojoUnitTest.java
datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoIntegrationTest/sodastore/output/com/sap/cloud/sdk/datamodel/rest/sodastore/model/NewSoda.java
datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoIntegrationTest/sodastore/output/com/sap/cloud/sdk/datamodel/rest/sodastore/model/Soda.java
datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoIntegrationTest/sodastore/output/com/sap/cloud/sdk/datamodel/rest/sodastore/model/UpdateSoda.java
datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoUnitTest/testInvocationWithUnexpectedApiMaturity/pom.xml
pom.xml

This pull request fixes the tests for our 3 maven plugins. Currently, the tests are **not executed**. This is because they are defined using JUnit 4, but our JUnit execution engine (defined here) only executes JUnit 5 tests. Unfortunately, this goes completely undetected.
* Migrate maven plugin tests to JUnit 5
* Apply a bit of workaround code to make the JUnit4-based `MojoRule` from `maven-plugin-test-harness` work inside the JUnit 5 tests
* Fix any broken test code
* Ban JUnit 4 via dependency rule
* ~Ban import statements for JUnit 4 test annotation (`org.junit.Test`) via PMD rule~ 
* Moved to separate PR
* This is done to enforce that in the maven plugin modules, where we still need to have JUnit 4 on the classpath, it can't be used to annotate tests
Alternatively to:
> Migrate maven …

fix: [DevOps] Fix Broken Maven Plugin Tests and Ban JUnit4

---

.github/workflows/continuous-integration.yaml

This PR addresses the issue of failing Surefire reports on pull requests created from forks and from GitHub Apps like dependabot. The changes in this PR modify the continuous integration workflow to handle these cases correctly.
This PR is related to the backlog item [#419 Fix dependency update PR test-report error](https://github.com/SAP/cloud-sdk-java-backlog/issues/419).
Please review the changes in the continuous integration workflow file and ensure that the updated condition for the "Test Report" step is correct.

fix: Fix Surefire reports on Dependabots PRs

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java

Related BLI
* https://github.com/SAP/cloud-sdk-java-backlog/issues/412
We've noticed an incompatibility with SJB (**2.2.0**):
* They haven't updated to service-binding-lib [`0.10.3`](https://github.com/SAP/btp-environment-variable-access/releases/tag/0.10.3) yet. At runtime class loading issues will occur.
More context:
* To enable SJB you need to set service-binding-lib `scope=provided`
* When using `scope=compile` duplicate entries in class-path will break class loading.

Make Service Binding Library usage backwards-compatible

---

cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Wrapper.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5Cache.java
cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5CacheTest.java
cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapperTest.java
release_notes.md

This PR ports the change done in #218 to the HttpClient 5. Probably, this was just forgotten to do with the original PR.

fix: [HttpClient] Fix Destination Reference in ApacheHttpClient5Wrapper

---

cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoader.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoaderTest.java
release_notes.md

Previously, any invocation to `proxy(..)` on `DefaultHttpDestination.Builder` was meaningless, if the destination has the proxy type `ON_PREMISE, because the value would be overriden when adding the on-prem logic.
This change is handy for local testing (where you need to set the proxy URL to localhost) or any scenario where a non-default connectivity proxy config is used.

fix: [Destinations] Allow for Custom Proxy Config in ON_PREMISE Destinations

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultRfcDestination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/Destination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/EnvVarDestinationLoader.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/RfcDestination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/RfcDestinationProperties.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/CustomDestinationRegistrationTest.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultDestinationTest.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultRfcDestinationTest.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceFactory.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceFactoryTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTest.java
release_notes.md

Closes SAP/cloud-sdk-java-backlog#315
- Deprecated the `RfcDestination` interface and all associated usages. The replacement is `Destination`.
Please review the changes and ensure that all deprecated usages have been correctly marked and that the replacements are correctly suggested.

chore: Deprecate `RfcDestination` and associated usages

---

.pipeline/scripts/release_notes_automation.py
.pipeline/scripts/release_notes_template.md
docs/how-to/release.md
release_notes.md

This pull request includes changes to the release notes automation script, release notes template, release documentation, and the release notes themselves. The primary change is the removal of the dependency updates section from the release notes and the associated cleanup function from the automation script.
1. **.pipeline/scripts/release_notes_automation.py**: Removed the `clean_up_dependency_updates` function which was responsible for removing empty dependency update sections from the release notes. This function is no longer needed as the dependency updates section has been removed from the release notes template.
2. **.pipeline/scripts/release_notes_template.md**: Removed the dependency updates section from the release notes template. This section was previously used to list updates …

feat: Remove dependency updates section from release notes and automation script

---

cloudplatform/connectivity-dwc/pom.xml
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcHeaderUtils.java
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/security/DwcAuthTokenFacade.java
cloudplatform/connectivity-dwc/src/main/resources/META-INF/services/com.sap.cloud.sdk.cloudplatform.security.AuthTokenFacade
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/security/DwcAuthTokenFacadeTest.java
cloudplatform/security/src/main/resources/META-INF/services/com.sap.cloud.sdk.cloudplatform.security.AuthTokenFacade
cloudplatform/security/src/main/resources/META-INF/services/com.sap.cloud.sdk.cloudplatform.security.secret.SecretStoreFacade
cloudplatform/security/src/main/resources/META-INF/services/com.sap.cloud.sdk.cloudplatform.security.user.UserFacade
release_notes.md

SAP/cloud-sdk-java-backlog#424.
I think we just forgot to implement this earlier. This change makes our `AuthTokenAccessor` actually return a token in the DwC case. Without this change, one always gets an exception (unless using CAP).

fix: DwC Auth Token not available

---

cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcHeaderUtils.java
cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/tenant/DwcTenantFacade.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/DwcHeaderUtilsTest.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/tenant/DwcTenantFacadeTest.java
release_notes.md

Customer issue: https://sap-cpe.slack.com/archives/C0115K14FMG/p1710143831812869
At the moment, DwC does not support domains for IAS-only tenants.
As such, our DwC specific tenant retrieval logic fails.
This PR fixes this issue by making the subdomain optional while resolving the tenant information from the DwC headers.
**NOTE**: The DwC colleagues are working on also providing the tenant's subdomain as part of [this issue](https://github.tools.sap/deploy-with-confidence/issues/issues/2147) (they said they will be working on this somewhen in Q2/24).

fix: Allow DwC Tenant without Subdomain

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java

Related
https://github.com/orgs/SAP/projects/62/views/5?pane=issue&itemId=55522157
Not sure whether this brings any benefit. But the user was unable to locate the implementation classes by themselves.

Add implementation reference to interface parameter declaration in JavaDoc

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandler.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestinationBuilderProxyHandlerTest.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationService.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ConnectivityServiceTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingDestinationLoaderTest.java

This PR improves the error handling in case adding on-premise headers failed. The error message is now more expressive and prepares a future update to change the behavior to be more consistent with the rest of the SDk.

Improve error handling for Missing Connectivity Proxy information

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MultiUrlPropertySupplier.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/MultiUrlPropertySupplierTest.java
release_notes.md

SAP/cloud-sdk-java-backlog#416
Some Business Logging service endpoints contain redundant paths that get appended again when generated clients are called, creating bad paths. The fix removes paths from the returned URLs for Business Logging service, so they may be later appended without conflict.

Fix: Business Logging Service Binding removed from Endpoint URLs

---

.github/workflows/dependabot-automerge.yaml

This PR fixes an issue with our pipeline where our main build wouldn't be triggered from commits that are stemming from our "Dependabot Automerging" logic.

fix: Run CI after Dependabot Auto Merges

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationKeyStoreComparator.java
release_notes.md

Follow-up from #341
Not critical, since NPE is being caught by default.
However it's easily possible to avoid throwing the exception.

fix: Redundant NPE in `DefaultHttpDestination#equals` and `#hashCode`

---

cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpClientCache.java
cloudplatform/connectivity-apache-httpclient4/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpClientCacheTest.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5Cache.java
cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5CacheTest.java
release_notes.md

SAP/cloud-sdk-java-backlog#430.

feat: [Destinations] Increase Http Client Cache Duration

---

datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestActionTest.java
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/ActionRequestBuilder.java
datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/SingleValueActionRequestBuilderTest.java
datamodel/odata-v4/odata-v4-core/src/test/resources/SingleValueActionRequestBuilderTest/ActionNullEntityRequestBody.json
release_notes.md

closes SAP/cloud-sdk-java-backlog#441
Customer support issue: [ActionRequestBuilder.serialize throws NullPointerException if parameter is null](https://github.com/SAP/cloud-sdk-java/issues/401#top)

Fix NPE in ActionRequestBuilder.serialize

---

.gitignore

File used by [jenv](https://github.com/jenv/jenv). Low prio obviously

chore: [DevOps] Add .java-version to .gitignore

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/IdentityAuthenticationServiceBindingDestinationLoaderTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2IntegrationTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
release_notes.md

This PR changes token flows to IAS to always send the `app_tid` parameter. This is required in case an IAS tenant is used across multiple different subaccounts. We got confirmation that it is safe to always send this, thus adding it in.

feat: [Destinations] Always send APP_TID for IAS Token Requests

---

.github/actions/pr-is-mergeable/action.yaml
.github/actions/workflow-succeeded/action.yaml
.github/workflows/perform-release.yml

This PR fixes [our `Perform Release`](https://github.com/SAP/cloud-sdk-java/actions/workflows/perform-release.yml) workflow in the following ways:
1. When we are checking, whether the Code PR (e.g. #408) is mergeable, we are now excluding the `BlackDuck Scan` and the `Run Security Rating` steps from the checks.
This is because the regular PR CI (which will be triggered on the commit that bumps the SDK's version to the next SNAPSHOT, i.e. the commit **after** the one that is to be released) won't run BlackDuck and the Security Rating.
Therefore, those steps will be skipped and should not be considered when we are verifying whether the PR is mergeable.
2. We are introducing a dedicated check to see whether [our `Continuous Integration`](https://github.com/SAP/cloud-sdk-java/actions/workflows …

fix: perform release workflow

---

.github/workflows/dependabot-automerge.yaml

This PR refactors our automated PR merging for Dependabot PRs in a way that the workflow is triggered on a schedule (every Monday, after Dependabot might have opened new PRs) instead of triggering right after the PR creation.
The old approach has shown to be non-functioning as the workflow was triggered by an external user (i.e. Dependabot), which (we assume) prevented the workflow from accessing any our secrets.
As a consequence, the workflow always failed.
This updated approach does not run into that issue as the workflow is not triggered by an external user.
So we can safely access all of our secrets.
The updated workflow has been tested here: [Workflow Run](https://github.com/SAP/cloud-sdk-java/actions/runs/8878953514/job/24375619632)

refactor: Dependabot Auto Merge GH Workflow

---

.github/workflows/cache-maven-dependencies.yaml
.github/workflows/continuous-integration.yaml
pom.xml

This PR introduces a new GH workflow that periodically (once per week) updates our cached Maven Dependencies.
That way, we are making sure that our cache is never older than 1 week, which reduces the amount of non-up-to-date dependencies in our `Continuous Integration` runs.

feat: Cron Workflow to Update Maven Dependency Cache

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationHeaderProviderTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/ConnectivityServiceTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java

Minor improvement to the readability of stack traces produced by errors from header providers (e.g. on-prem headers failed)
<details><summary>Before:</summary>
```
java.lang.RuntimeException: Test exception
at com.sap.cloud.sdk.cloudplatform.connectivity.DestinationHeaderProviderTest.lambda$testExceptionsAreHandled$4(DestinationHeaderProviderTest.java:75)
at com.sap.cloud.sdk.cloudplatform.connectivity.DefaultHttpDestination.lambda$getHeadersFromHeaderProviders$1(DefaultHttpDestination.java:199)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at …
```

chore: [Destinations] Improve Header Provider Error Handling

---

cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceFactory.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceFactoryTest.java
release_notes.md

fixes #428 
This PR fixes a regression where auth token sent by the Destination service wouldn't be stored in the `cloudsdk.authTokens` (`DestinationProperty.AUTH_TOKENS`) property for non-HTTP destinations.

fix: AuthToken Regression

---

cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/AbstractHttpClientFactory.java

I was wondering why this was part of the `HttpClientWrapper`, when I realized - most likely we do not and cannot reuse connection manager between multiple instances of `HttpClient`:
https://github.com/SAP/cloud-sdk-java/blob/f0dd44016892ef1f1fbd758b83c84d00948f9854/cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java#L38-L48
To address this in the source code, I want to add a comment.

Add comment about `ConnectionManager` cardinality in `AbstractHttpClientFactory`

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplier.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/SecurityLibWorkarounds.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplierTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/SecurityLibWorkaroundsTest.java
release_notes.md

This PR improves the credential type detection to deal with a lowercase variant of `x509_attested`, which will be used by XSUAA.

feat: Support ZTIS with XSUAA

---

cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServiceOptions.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliersTest.java
release_notes.md

SAP/cloud-sdk-java-backlog#454
IAS doesn't allow for sending `clientid:client-id:apptid:tenant-id`. We might have built this based on some older documentation from IAS that in the meanwhile got updated. Or I made a copy/paste mistake when copying the requirements for the parameters into our ticket 😅
Anyhow, deprecating the non-functional option.

Deprecate non functional IAS option

---

cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/ThreadContextExecutor.java

Reduce unnecessary exception in `ThreadContextExecutor`

---

datamodel/openapi/openapi-generator-maven-plugin/src/test/resources/DataModelGeneratorMojoIntegrationTest/sodastore/output/com/sap/cloud/sdk/datamodel/rest/sodastore/api/DefaultApi.java
datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/libraries/resttemplate/api.mustache
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-vendor-extension-json/output/com/sap/cloud/sdk/services/apiclassvendorextension/api/AwesomeSodaApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-vendor-extension-json/output/com/sap/cloud/sdk/services/apiclassvendorextension/api/AwesomeSodasApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-vendor-extension-json/output/com/sap/cloud/sdk/services/apiclassvendorextension/api/DefaultApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-vendor-extension-yaml/output/com/sap/cloud/sdk/services/apiclassvendorextension/api/DefaultApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/api/DefaultApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-uppercase-file-extension/output/com/sap/cloud/sdk/services/uppercasefileextension/api/AwesomeSodaApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-uppercase-file-extension/output/com/sap/cloud/sdk/services/uppercasefileextension/api/AwesomeSodasApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-uppercase-file-extension/output/com/sap/cloud/sdk/services/uppercasefileextension/api/DefaultApi.java
release_notes.md

[`google-java-format` cannot format files that have comments in imports](https://github.tools.sap/AI/ai-core-sdk-java/pull/59), furthermore [OpenAPI doesn't specify this comment in their api.mustache file](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/api.mustache#L8).

Remove `//NOPMD` on OpenAPI generated imports

---

.github/workflows/continuous-integration.yaml

Improvement discovered while working on [Added test coverage](https://github.tools.sap/AI/ai-core-sdk-java/pull/62#top) in the AI SDK
This step was used to [create a Jacoco badge](https://github.com/SAP/cloud-sdk-java/commit/4419cc5539b4aad1367c0c2d2cc77c6a160d0be7#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1R124) which we no longer need.
The functionality of the `Coverage` step is not affected since the `Run Unit Tests` step is unchanged.

Removed `Test Report` step

---

datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/pojo.mustache
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/input-spec-with-anyof-oneof/output/com/sap/cloud/sdk/services/anyofoneof/model/RootObject.java
release_notes.md

Fix a bug introduced in https://github.com/SAP/cloud-sdk-java/pull/441 (released as `5.10.0`)

Fix incorrect camelCase when generating list accessors for OpenAPI

---

cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationRetrievalStrategy.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationRetrievalStrategyResolver.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapter.java
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceOptionsAugmenter.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationRetrievalStrategyResolverTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapterTest.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTest.java
release_notes.md

This PR enhances the Cloud SDK to support [Destination Fragments](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/extending-destinations-with-fragments).

feat: [Destinations] Support Fragments

---

cloudplatform/connectivity-ztis/pom.xml

SAP/cloud-sdk-java-backlog#448.
Fixes [BDSA-2024-5199](https://sap.blackducksoftware.com/api/vulnerabilities/BDSA-2024-5199)

Fix vulnerability

---

datamodel/openapi/openapi-generator-maven-plugin/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorMojo.java
datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGenerator.java
datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/model/GenerationConfiguration.java
datamodel/openapi/openapi-generator/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorUnitTest.java
release_notes.md

~It would be good if we checked for any unexpected files before blindly deleting user-provided paths.~
To stay safe, we should only delete what was being generated, according to the configuration provided.
\* Also I want us to retain "hidden" files (with `.`-prefix), to keep custom files like `.gitignore` or `.openapi-generator-ignore`)

[OpenAPI Generator] When deleting files, only consider specific packages

---

cloudplatform/connectivity-ztis/pom.xml
release_notes.md

The approach of only using `dependencyManagement` doesn't work, as this only affects the version within the module itself, not the version when using the module.
Unfortunately, we can only override the version by referencing transitive dependencies explicitly. We could add it to the main BOM, but that only fixes it when the BOM is used by customers.

fix: gRPC Version

---

.github/dependabot.yaml
cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/ThreadContextDecorator.java
cloudplatform/cloudplatform-core/src/main/java/com/sap/cloud/sdk/cloudplatform/thread/ThreadContextListener.java
codestyle/checkstyle.xml
datamodel/odata-v4/odata-v4-core/src/main/java/com/sap/cloud/sdk/datamodel/odatav4/core/BoundFunction.java
pom.xml

Checkstyle was updated on the AI SDK. I'm porting the update to Cloud SDK

Updated checkstyle to `10.17.0`

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/BtpServicePropertySuppliers.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplier.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Options.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultOAuth2PropertySupplierTest.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBuilderTest.java
release_notes.md

Allows for customizing the timeout for token retrieval.
**API Design**
```java
var opts = ServiceBindingDestinationOptions
.forService(...)
.withOption(
OAuth2Options.TokenRetrievalTimeout.of(TimeLimiterConfiguration.of(Duration.ofSeconds(100))))
.build();
ServiceBindingDestinationLoader.defaultLoaderChain().getDestination(opts);
```

feat: [OAuth2] Enable OAuth Timeout Customization

---

README.md
cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapter.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapterTest.java
release_notes.md

This fixes a bug that would cause HTTP connections to stay open in case the destination service returns an error with payload. Which is the case for e.g. 404 responses.

fix: Destination Service Error Handling

---

cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationService.java
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTest.java
release_notes.md

#558
We deprecated public `DestinationService` method `public Try<Iterable<Destination>> tryGetAllDestinations( @Nonnull final DestinationOptions options )`. The user wants an alternative to ensure the destination lookup happens for correct tenant.

feat: [DestinationService] Allow optional retrieval-strategy (tenant) in getAllDestinationProperties

---

cloudplatform/cloudplatform-core/src/test/java/com/sap/cloud/sdk/cloudplatform/requestheader/DefaultRequestHeaderContainerTest.java

When writing [the response here](https://github.com/SAP/cloud-sdk-java/pull/568#discussion_r1736040166) I was wondering how we check for (non-)nullability for `getHeaderValues(String)` returned object.

chore: Add nonnull test case assertions for `DefaultRequestHeaderContainer`

---

cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/DwcHeaderUtils.java
cloudplatform/connectivity-dwc/src/test/java/com/sap/cloud/sdk/cloudplatform/security/DwcAuthTokenFacadeTest.java
release_notes.md

This PR is for fixing the issue SAP#557. The code change is mainly an enhancement on top of SAP#337 to include dwc-ias-jwt in header as auth token as well. dwc-ias-jwt is the key used for auth token when dwc is integrated with ias for authentication.
https://github.com/SAP/cloud-sdk-java/issues/557
Please provide a short description of what your change does and why it is needed.
The scenario is to propagate user principal from DwC+IAS to an xsuaa based reused service. 
Under such case, the authorization token attached to DwC headers used the key "dwc_ias_jwt". It is different from what approuter would attach (which is Authorization) or DwC+XSUAA would attach(which is dwc_jwt).
This fix is built on top of the fix [#337](https://github.com/SAP/cloud-sdk-java/pull/337). The fix #337 handles …

fix: issue #557: DwC Auth Token not available (DwC + IAS)

---

.github/workflows/continuous-integration.yaml
.github/workflows/prepare-release.yaml

Probably a consequence of updating the `maven-site-plugin` recently.
5.12.0 release was successful with this fix

fix: [DevOps] JavaDoc generation

---

datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClient.java
datamodel/openapi/openapi-core/src/test/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClientViaConstructorTest.java
release_notes.md

https://github.com/SAP/cloud-sdk-java/issues/582
Please provide a short description of what your change does and why it is needed.
ApiClient class is using incorrect encoder class for Query parameters encoding.
Current version is based on URLEncoder.encode((String)values.get(i), "utf8")) which is meant to encode URI (i.e path variables), but does not work well for query parameters because the encoding requirements there are different (i.e. whitespace should not be encoded as "+", but with %20).
The intent is to change the encoding to org.springframework.web.util.UriUtils.encodeQueryParam((String)values.get(i), "utf8"))

Issue 582: Replace query parameters encoder

---

.github/actions/deploy-snapshot/action.yaml
.github/workflows/cache-maven-dependencies.yaml
.github/workflows/continuous-integration.yaml
.github/workflows/perform-release.yml

The setup-java action now supports setting up SAPMachine as the openJDK distribution of choice, so we should use it 🚀

Use SAPMachine for building in CI

---

datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/libraries/resttemplate/api.mustache
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-for-ai-sdk/output/com/sap/cloud/sdk/services/builder/api/AwesomeSodaApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-for-ai-sdk/output/com/sap/cloud/sdk/services/builder/api/AwesomeSodasApi.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-for-ai-sdk/output/com/sap/cloud/sdk/services/builder/api/DefaultApi.java

Supports this PR: SAP/ai-sdk-java#201

Update Code Generator for AI SDK

---

datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/OneOf.java
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/OneOfWithDiscriminator.java
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/OneOfWithDiscriminatorAndMapping.java
datamodel/openapi/openapi-api-sample/src/main/resources/sodastore.yaml
datamodel/openapi/openapi-api-sample/src/test/java/com/sap/cloud/sdk/datamodel/openapi/sample/api/OneOfDeserializationTest.java
datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/GenerationConfigurationConverter.java
datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/model/GenerationConfiguration.java
datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/oneof_interface.mustache
datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/typeInfoAnnotation.mustache
datamodel/openapi/openapi-generator/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorIntegrationTest.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/generate-apis/output/test/OneOfWithDiscriminator.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/generate-apis/output/test/OneOfWithDiscriminatorAndMapping.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/oneof-interfaces-disabled/output/test/OneOfWithDiscriminator.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/oneof-interfaces-disabled/output/test/OneOfWithDiscriminatorAndMapping.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/oneof-interfaces-enabled/input/sodastore.yaml
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/oneof-interfaces-enabled/output/test/OneOf.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/oneof-interfaces-enabled/output/test/OneOfWithDiscriminator.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/oneof-interfaces-enabled/output/test/OneOfWithDiscriminatorAndMapping.java

Follow up to #647, see [this comment](https://github.com/SAP/cloud-sdk-java/pull/647#discussion_r1860833002)

feat: [OpenAPI] Improved OneOf Support

---

cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Wrapper.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5Factory.java
cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapperTest.java
datamodel/openapi/openapi-core/src/test/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClientViaConstructorTest.java
release_notes.md

Fix: TLS Upgrade config propagates to RestTemplate

---

.github/workflows/main-build.yaml

The repo secret formally known as `ARTIFACTORY_TOKEN` was in fact just a password. Update this to a more fitting name.

Improve naming of secret in main-build-workflow.

---

.github/workflows/perform-release.yml

The release script was pointing to the last release when making checks in the perform release. If it did not exist, it still succeeded.

Fix perform release

---

pom.xml

Annotation processing is not working anymore locally in the IDE
Without the `<annotationProcessorPaths>` config:
* JDK 17 (✔️ IntelliJ ✔️ MVN)
* JDK 22 (✔️ IntelliJ ✔️ MVN)
* JDK 23 (✔️ IntelliJ 🚫 MVN)
With the `<annotationProcessorPaths>` config:
* JDK 17 (🚫 IntelliJ ✔️ MVN)
* JDK 22 (🚫 IntelliJ ✔️ MVN)
* JDK 23 (🚫 IntelliJ ✔️ MVN)
---
With current branch:
* JDK 17 (✔️ IntelliJ ✔️ MVN)
* JDK 22 (✔️ IntelliJ ✔️ MVN)
* JDK 23 (✔️ IntelliJ ✔️ MVN)

fix: [DevOps] Remove annotation processing for local compilation

---

datamodel/openapi/openapi-generator/src/main/java/com/sap/cloud/sdk/datamodel/openapi/generator/GenerationConfigurationConverter.java
datamodel/openapi/openapi-generator/src/main/resources/openapi-generator/mustache-templates/pojo.mustache
datamodel/openapi/openapi-generator/src/test/java/com/sap/cloud/sdk/datamodel/openapi/generator/DataModelGeneratorIntegrationTest.java
datamodel/openapi/openapi-generator/src/test/resources/DataModelGeneratorIntegrationTest/api-class-for-ai-sdk/output/com/sap/cloud/sdk/services/builder/model/Soda.java

SAP/cloud-sdk-java-backlog#170.
To fully replace `List<BigDecimal>` with `float[]` we need to adapt the generated model classes on a template layer.
`

Adapting equals and  hashcode generation for float[]

---

datamodel/openapi/openapi-api-sample/pom.xml
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/FantaFlavor.java
datamodel/openapi/openapi-api-sample/src/main/java/com/sap/cloud/sdk/datamodel/openapi/sample/model/FlavorType.java
datamodel/openapi/openapi-api-sample/src/main/resources/sodastore.yaml
datamodel/openapi/openapi-api-sample/src/test/java/com/sap/cloud/sdk/datamodel/openapi/sample/api/OneOfDeserializationTest.java

AI/ai-sdk-java-backlog#681.
We aim to test if the [proposed OpenAPI spec](https://github.tools.sap/AI/llm-orchestration/pull/1163/files) definition may hinder Java SDK development.  
Specifically, the specification contains properties that may be `oneOf` types, including both primitive and complex types. The tests are designed to verify the deserialization for both `oneOf` and `anyOf` scenarios.  
Note: The spec doesn't contain `anyOf` case yet.

test: [OpenAPI-Gen] Deserialising `oneOf` and `anyOf` with array of objects  

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
release_notes.md

Improves our code to explicitly throw in case the subdomain is missing. The IAS server will reject any requests where `tenantId != provider && subdomian == null`. This PR throws an explicit error instead of allowing the request.
See #736

feat: [IAS] Harden IAS Subdomain Resolution in OAuth2Service

---

cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpClientCache.java
cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientAccessor.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5Accessor.java
cloudplatform/connectivity-apache-httpclient5/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/ApacheHttpClient5CacheBuilder.java

Issue: https://github.com/SAP/cloud-sdk-java/issues/755
Fix the javadoc to match the actual TTL in client cache.

docs: [Connectivity-Apache-Client4/5] Upate Cache TTL in javadoc

---

cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2IntegrationTest.java

SAP/cloud-sdk-java-backlog#474
There have been user issues where the underlying problem is that the SaaS dependencies were not setup correctly, resulting in a 401 - Bad Credentials error when the user was doing a OAuth2 token request.
This PR extends the relevant error message in this case to include a hint that the reason for the 401 might be a wrong setup of the SaaS registry.

feat: Extend error message for 401 errors

---

cloudplatform/connectivity-ztis/pom.xml
pom.xml

Add explicit dependency to connectivity-ztis pom to fix CVE-2025-48734.
Related customer issue: 
- https://github.com/SAP/cloud-sdk-java/issues/843

chore: Fix CVE-2025-48734

---

.github/workflows/deploy-snapshot.yaml
dependency-bundles/bom/pom.xml
dependency-bundles/modules-bom/pom.xml
pom.xml

[Successful run](https://github.com/SAP/cloud-sdk-java/actions/runs/16933171659)

fix: [DevOps] Snapshot release

---

cloudplatform/connectivity-destination-service/pom.xml
cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceTest.java
cloudplatform/resilience4j/pom.xml
cloudplatform/resilience4j/src/main/java/com/sap/cloud/sdk/cloudplatform/resilience4j/DefaultCircuitBreakerProvider.java
cloudplatform/resilience4j/src/main/java/com/sap/cloud/sdk/cloudplatform/resilience4j/Resilience4jDecorationStrategy.java
cloudplatform/resilience4j/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience4j/CircuitBreakerTest.java
cloudplatform/resilience4j/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience4j/RetryTest.java
dependency-bundles/bom/pom.xml
release_notes.md

SAP/cloud-sdk-java-backlog#476.
- previously: `CircuitBreaker is OPEN and does not permit further calls`
- now: `Failed to get destination ... Caused by: Destination could not be found for path destination-configuration/v1/destinations/xxxx.`
⚠️ Note that there is a bug in the circuit breaker. **All destination calls use the same circuit breaker.**

fix: CircuitBreaker stack-trace

---

cloudplatform/connectivity-destination-service/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceOptionsAugmenter.java

Small improvement requested by a user.

[Destinations] Improve Options Class
